spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: changeme
    username: changeme
    password: changeme
    driverClassName: org.postgresql.Driver
  rabbitmq:
    host: changeme
    port: 5672
    password: changeme
    username: changeme
    rbp:
      exchange: iot.exchange
      queue: iot.queue
      routingkey: iot.routingkey
    feedback:
      exchange: iot.feedback.exchange
      queue: iot.feedback.queue
      routingkey: iot.feedback.routingkey


server:
  error:
    include-stacktrace: never

weather:
  apiKey: changeme
